repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: (^docs/)
    -   id: end-of-file-fixer
        exclude: (^docs/)
    -   id: check-docstring-first
        exclude: (^docs/)
    -   id: check-yaml
        exclude: (^docs/)
    -   id: debug-statements
        exclude: (^docs/)
    -   id: double-quote-string-fixer
        exclude: (^docs/)
    -   id: name-tests-test
        exclude: (^docs/)
    -   id: requirements-txt-fixer
        exclude: (^docs/)

# Flake rules: https://lintlyci.github.io/Flake8Rules/
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        exclude: (^docs/)
        additional_dependencies: [flake8-typing-imports==1.1.0]
        # E501 line too long
        # E722 do not use bare 'except
        # F541 f-string is missing placeholders
        # E741 ambiguous variable name 'l'
        args: ['--config=setup.cfg', '--ignore=E501,E722,F541,E741']

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
        exclude: (^docs/)

#-   repo: https://github.com/asottile/reorder_python_imports
#    rev: v2.4.0
#    hooks:
#    -   id: reorder-python-imports
##        args: [--py3-plus]

#-   repo: https://github.com/thclark/pre-commit-sphinx
#    rev: 0.0.1
#    hooks:
#    -   id: build-docs
#        args: ['--cache-dir', 'docs/doctrees', '--html-dir', 'docs/build/html', '--source-dir', 'docs/source']
#        language_version: python3
