name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          python -m tox
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - repo: https://github.com/thclark/pre-commit-sphinx
        rev: 0.0.1
        hooks:
          - id: build-docs
            args: ['--cache-dir', 'docs/doctrees', '--html-dir', 'docs/build/html', '--source-dir', 'docs/source']
            language_version: python3