name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  go-tests:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

#      - name: Security Scan
#        id: Bridgecrew
#        uses: bridgecrewio/bridgecrew-action@master
#        with:
#          api-key: ${{ secrets.BRIDGECREW_API_KEY }}

